import type { Metadata } from "next";
import {Cairo} from "next/font/google";
import "./globals.css";
import Navbar from "./_sections/Navbar";


const cairo = Cairo({
  subsets: ["arabic"]
})

export const metadata: Metadata = {
  title: "مجالس",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cairo.className} antialiased`}>
          <Navbar/>
        {children}
      </body>
    </html>
  );
}
